services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./inventa_tech:/var/www/html/inventa_tech
    depends_on:
      - db

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ***REDACTED***
      POSTGRES_DB: inventa_tech
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
